### ISSUE TITLE
Remove "packages" from Flutter build_runner commands in documentation

### ISSUE THREAD

**Issue by keremenesersoy** [Deatsilence/stocket#36]
In many places, the `flutter packages pub` command is still used for running `build_runner`, like in:
`flutter packages pub run build_runner build`

However, the packages keyword is deprecated and no longer necessary. The correct command should be:
`flutter pub run build_runner build`

This change would simplify the usage and avoid confusion for newer Flutter developers.

**Comment by Deatsilence** [comment]
Thanks for your interest and advice. It changed @keremenesersoy
